# Generated by Django 4.1 on 2025-05-09 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fm_user", "0001_initial"),
        ("fm_goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "oid",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Order Number",
                    ),
                ),
                ("odate", models.DateTimeField(auto_now=True, verbose_name="Time")),
                ("oIsPay", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "ototal",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Total Price"
                    ),
                ),
                (
                    "oaddress",
                    models.CharField(max_length=150, verbose_name="Order Address"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_user.userinfo",
                        verbose_name="Order User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unpaid Order",
                "verbose_name_plural": "Unpaid Order",
            },
        ),
        migrations.CreateModel(
            name="OrderDetailInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        default=None, max_length=20, verbose_name="Buyer Username"
                    ),
                ),
                (
                    "shopername",
                    models.CharField(
                        default="", max_length=20, verbose_name="Seller Username"
                    ),
                ),
                (
                    "datatime",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Transaction Time"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Product Price"
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Product Quantity")),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_goods.goodsinfo",
                        verbose_name="Product",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_order.orderinfo",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paid Order",
                "verbose_name_plural": "Paid Order",
            },
        ),
    ]
