# Generated by Django 4.1 on 2025-05-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fm_user", "0003_alter_userinfo_options"),
        ("fm_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderdetailinfo",
            options={
                "ordering": ["order", "goods"],
                "verbose_name": "Order Detail",
                "verbose_name_plural": "Order Detail",
            },
        ),
        migrations.AlterModelOptions(
            name="orderinfo",
            options={
                "ordering": ["-odate"],
                "verbose_name": "Order",
                "verbose_name_plural": "Order",
            },
        ),
        migrations.RemoveField(
            model_name="orderdetailinfo",
            name="datatime",
        ),
        migrations.RemoveField(
            model_name="orderdetailinfo",
            name="shopername",
        ),
        migrations.RemoveField(
            model_name="orderdetailinfo",
            name="username",
        ),
        migrations.AlterField(
            model_name="orderdetailinfo",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="fm_order.orderinfo",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="fm_user.userinfo",
                verbose_name="Order User",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderdetailinfo",
            constraint=models.UniqueConstraint(
                fields=("order", "goods"), name="unique_order_item"
            ),
        ),
    ]
