# Generated by Django 4.1 on 2025-05-09 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                ("ttitle", models.CharField(max_length=20, verbose_name="Category")),
            ],
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Type",
            },
        ),
        migrations.CreateModel(
            name="GoodsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                (
                    "gtitle",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Product Name"
                    ),
                ),
                (
                    "gpic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fm_goods/image/%Y/%m",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "gprice",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Product Price"
                    ),
                ),
                (
                    "gunit",
                    models.CharField(max_length=20, verbose_name="Seller Username"),
                ),
                ("gclick", models.IntegerField(default=0, verbose_name="Click Count")),
                (
                    "gjianjie",
                    models.CharField(max_length=200, verbose_name="Brief Introduction"),
                ),
                ("gkucun", models.IntegerField(default=0, verbose_name="Inventory")),
                (
                    "gcontent",
                    tinymce.models.HTMLField(max_length=200, verbose_name="Details"),
                ),
                (
                    "gtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_goods.typeinfo",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Product",
            },
        ),
        migrations.CreateModel(
            name="GoodsContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                (
                    "ctitle",
                    models.CharField(max_length=20, verbose_name="Product Name"),
                ),
                (
                    "cpic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fm_goods/image/%Y/%m",
                        verbose_name="Upload Image",
                    ),
                ),
                (
                    "cusername",
                    models.CharField(max_length=20, verbose_name="Buyer Username"),
                ),
                (
                    "clogo",
                    models.CharField(
                        default=None, max_length=200, verbose_name="Buyer Avatar"
                    ),
                ),
                (
                    "cuser_content",
                    tinymce.models.HTMLField(
                        max_length=200, verbose_name="User Comment"
                    ),
                ),
                (
                    "date_publish",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Publication Time"
                    ),
                ),
                (
                    "cgoodsname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_goods.goodsinfo",
                        verbose_name="Related Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Comment",
                "verbose_name_plural": "Product Comment",
            },
        ),
        migrations.CreateModel(
            name="ContentChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                (
                    "ctitle",
                    models.CharField(max_length=20, verbose_name="Product Name"),
                ),
                (
                    "cusername",
                    models.CharField(max_length=20, verbose_name="Commenter Username"),
                ),
                (
                    "cusername1",
                    models.CharField(max_length=20, verbose_name="Replier Username"),
                ),
                (
                    "ccontent_chart",
                    tinymce.models.HTMLField(
                        max_length=200, verbose_name="Comment Reply"
                    ),
                ),
                (
                    "date_publish",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Publication Time"
                    ),
                ),
                (
                    "ccontent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_goods.goodscontent",
                        verbose_name="Comment ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Reply",
                "verbose_name_plural": "Comment Reply",
            },
        ),
    ]
