# Generated by Django 4.1 on 2025-05-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fm_goods", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodscontent",
            name="cgoodsname",
        ),
        migrations.AlterModelOptions(
            name="goodsinfo",
            options={
                "ordering": ["gtitle"],
                "verbose_name": "Product",
                "verbose_name_plural": "Product",
            },
        ),
        migrations.RemoveField(
            model_name="goodsinfo",
            name="gtype",
        ),
        migrations.RemoveField(
            model_name="goodsinfo",
            name="isDelete",
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="gcontent",
            field=models.TextField(max_length=500, verbose_name="Details"),
        ),
        migrations.DeleteModel(
            name="ContentChart",
        ),
        migrations.DeleteModel(
            name="GoodsContent",
        ),
        migrations.DeleteModel(
            name="TypeInfo",
        ),
    ]
