# Generated by Django 4.1 on 2025-05-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fm_cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartinfo",
            options={
                "ordering": ["user", "goods"],
                "verbose_name": "Shopping Cart",
                "verbose_name_plural": "Shopping Cart",
            },
        ),
        migrations.AlterField(
            model_name="cartinfo",
            name="count",
            field=models.IntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AddConstraint(
            model_name="cartinfo",
            constraint=models.UniqueConstraint(
                fields=("user", "goods"), name="unique_cart_item"
            ),
        ),
    ]
