# Generated by Django 4.1 on 2025-05-09 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fm_goods", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=20, verbose_name="Product Name")),
                (
                    "username",
                    models.CharField(max_length=20, verbose_name="Recipient Name"),
                ),
                (
                    "username1",
                    models.CharField(max_length=20, verbose_name="Sender Name"),
                ),
                (
                    "person_number",
                    models.CharField(max_length=20, verbose_name="ID Number"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=20, verbose_name="Order Number"),
                ),
                (
                    "kuaidi",
                    models.CharField(max_length=20, verbose_name="Courier Type"),
                ),
                (
                    "kuaidi_number",
                    models.CharField(max_length=20, verbose_name="Tracking Number"),
                ),
                (
                    "address",
                    models.CharField(
                        default=None, max_length=50, verbose_name="Shipping Address"
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        default=None, max_length=50, verbose_name="Return Address"
                    ),
                ),
                (
                    "text",
                    tinymce.models.HTMLField(
                        default=None, max_length=200, verbose_name="Return Reason"
                    ),
                ),
                (
                    "passOrdefault",
                    models.BooleanField(default=False, verbose_name="Agree to Refund"),
                ),
                (
                    "date_publish",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Publication Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Order",
                "verbose_name_plural": "Return Order",
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uname",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "usex",
                    models.CharField(default="", max_length=10, verbose_name="Gender"),
                ),
                (
                    "uage",
                    models.CharField(default="", max_length=10, verbose_name="Age"),
                ),
                (
                    "upersonInf",
                    models.CharField(
                        default="", max_length=200, verbose_name="Personal Introduction"
                    ),
                ),
                (
                    "ulogo",
                    models.FileField(
                        default="default.jpg",
                        upload_to="images",
                        verbose_name="User Avatar",
                    ),
                ),
                ("upwd", models.CharField(max_length=40, verbose_name="Password")),
                (
                    "uemail",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "urealname",
                    models.CharField(
                        default="", max_length=20, verbose_name="Real Name"
                    ),
                ),
                (
                    "uzhengjian_type",
                    models.CharField(default="", max_length=20, verbose_name="ID Type"),
                ),
                (
                    "uzhengjian_tel",
                    models.CharField(
                        default="", max_length=18, verbose_name="ID Number"
                    ),
                ),
                (
                    "uzhengjian_img",
                    models.FileField(
                        default="",
                        upload_to="images/zhengjian_img",
                        verbose_name="ID Image",
                    ),
                ),
                (
                    "ucheck_passOrfail",
                    models.BooleanField(
                        default=False, verbose_name="Verification Approval"
                    ),
                ),
                (
                    "ushou",
                    models.CharField(
                        default="", max_length=20, verbose_name="Recipient Name"
                    ),
                ),
                (
                    "uaddress",
                    models.CharField(
                        default="", max_length=100, verbose_name="Address"
                    ),
                ),
                (
                    "uyoubian",
                    models.CharField(
                        default="", max_length=6, verbose_name="Postal Code"
                    ),
                ),
                (
                    "uphone",
                    models.CharField(
                        default="", max_length=11, verbose_name="Phone Number"
                    ),
                ),
                (
                    "uname_passOrfail",
                    models.BooleanField(default=True, verbose_name="Allow Login"),
                ),
            ],
            options={
                "verbose_name": "User Information",
                "verbose_name_plural": "User Information",
            },
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                (
                    "ctitle",
                    models.CharField(max_length=20, verbose_name="Product Name"),
                ),
                (
                    "cusername",
                    models.CharField(max_length=20, verbose_name="Buyer Username"),
                ),
                (
                    "cusername1",
                    models.CharField(max_length=20, verbose_name="Seller Username"),
                ),
                (
                    "ccontent_chart",
                    tinymce.models.HTMLField(
                        max_length=200, verbose_name="Message Content"
                    ),
                ),
                (
                    "ccheck",
                    models.BooleanField(
                        default=False, verbose_name="Message Read Status"
                    ),
                ),
                (
                    "date_publish",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Publication Time"
                    ),
                ),
                (
                    "cinformation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_user.userinfo",
                        verbose_name="Message",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Message",
                "verbose_name_plural": "User Message",
            },
        ),
        migrations.CreateModel(
            name="GoodsBrowser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "browser_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Browsing Time"
                    ),
                ),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_goods.goodsinfo",
                        verbose_name="Product ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fm_user.userinfo",
                        verbose_name="User ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Browsing History",
                "verbose_name_plural": "User Browsing History",
            },
        ),
    ]
