# Generated by Django 4.1 on 2025-05-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fm_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsbrowser",
            name="good",
        ),
        migrations.RemoveField(
            model_name="goodsbrowser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="information",
            name="cinformation",
        ),
        migrations.DeleteModel(
            name="ReturnInfo",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="uage",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="ucheck_passOrfail",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="ulogo",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="uname_passOrfail",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="upersonInf",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="urealname",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="uzhengjian_img",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="uzhengjian_tel",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="uzhengjian_type",
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="uemail",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.DeleteModel(
            name="GoodsBrowser",
        ),
        migrations.DeleteModel(
            name="Information",
        ),
    ]
