# Generated by Django 4.1 on 2025-05-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fm_user", "0002_remove_goodsbrowser_good_remove_goodsbrowser_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={
                "ordering": ["uname"],
                "verbose_name": "User Information",
                "verbose_name_plural": "User Information",
            },
        ),
    ]
