# Generated by Django 4.1 on 2025-05-10 10:00

from django.db import migrations

GROUPS = [
    {
        'name': 'regular_user',
    },
    {
        'name': 'seller',
    },
    {
        'name': 'admin',
    },
]


def add_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.create(
            name=group['name'],
        )


def remove_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.get(
            name=group['name']
        )
        group_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fm_user', '0003_alter_userinfo_options'),
    ]

    operations = [
        migrations.RunPython(
            add_group_data,
            remove_group_data
        )
    ]